[build]
  functions = "netlify/functions"  # Path to serverless functions
  publish = "static"               # Path to your static files (HTML, CSS, JS, etc.)

[functions]
  node_bundler = "esbuild"         # Use esbuild for bundling Node.js functions
