[build]
  functions = "./"                     
  publish = "./"                        
  ignore = "exit 0"                     

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html" 
  status = 200