[build]
  functions = "netlify/functions"   # Path to the functions directory (server.mjs)
  publish = "static"                 # Frontend assets are in the "static" directory

[functions]
  node_bundler = "esbuild"           # Use esbuild for bundling Node.js functions
  included_files = ["vin-bot/vinbot.js"]  # Include vinbot.js file from the vin-bot folder

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
