[build]
  functions = "netlify/functions"   # Path to the functions directory
  publish = "."                    # Serve files from the root directory
  ignore = "exit 0"                # Skip automatic plugin detection

[functions]
  node_bundler = "esbuild"          # Use esbuild for bundling Node.js functions
  included_files = ["vin-bot/vinbot.js"]  # Include vinbot.js from the vin-bot directory (if needed)

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200